modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Theoman9402/ae2tsc_AE2_Terminal_Scroll_Cycling/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Theoman9402/ae2tsc_AE2_Terminal_Scroll_Cycling"
logoFile = "ae2tsc.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2"
type = "required"
versionRange = "[19.2.17,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "ae2wtlib"
type = "required"
versionRange = "[19.4.1,)"
ordering = "AFTER"
side = "CLIENT"
